#!/usr/bin/env python3
"""
Script to add 'type: chandas' field for all entries that have (छ) in their form.
(छ) indicates Chandasa Prayoga.
"""

import json
import re
from pathlib import Path

def process_json_file(file_path):
    """
    Process the JSON file and add 'type: chandas' for entries with (छ) in form.
    Returns count of modified entries.
    """
    print(f"Reading file: {file_path}")

    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    modified_count = 0

    # Navigate through the nested structure
    for kanda in data.get('data', []):
        for varga in kanda.get('vargas', []):
            for shloka in varga.get('shlokas', []):
                for verb_group in shloka.get('verbs', []):
                    for entry in verb_group.get('entries', []):
                        form = entry.get('form', '')

                        # Check if form contains (छ)
                        if '(छ)' in form or '(छ)' in form:
                            # Add type field if not already present
                            if 'type' not in entry:
                                entry['type'] = 'chandas'
                                modified_count += 1
                                print(f"  ✓ Added type='chandas' to: {form}")
                            elif entry.get('type') != 'chandas':
                                entry['type'] = 'chandas'
                                modified_count += 1
                                print(f"  ✓ Updated type='chandas' for: {form}")

    if modified_count > 0:
        print(f"\nWriting changes back to file...")
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
        print(f"✓ Successfully modified {modified_count} entries")
    else:
        print("No entries found with (छ)")

    return modified_count

def main():
    """Main function."""
    file_path = Path(__file__).parent / 'output' / 'AkhyataChandrika_Autogenerated.json'

    print("=" * 70)
    print("Adding 'type: chandas' for entries with (छ) marker")
    print("=" * 70)
    print()

    if not file_path.exists():
        print(f"Error: File not found at {file_path}")
        return

    modified_count = process_json_file(file_path)

    print("\n" + "=" * 70)
    print(f"Summary: Modified {modified_count} entries in total")
    print("=" * 70)

if __name__ == '__main__':
    main()
