#!/bin/bash
# Test script to verify the backport functionality works correctly

echo "======================================================================"
echo "Testing Multiple Dhatu IDs Workflow"
echo "======================================================================"
echo ""

# Step 1: Collect multiple dhatu_ids
echo "Step 1: Collecting verbs with multiple dhatu_ids..."
python3 Scripts/collectMultipleDhatuIds.py \
    Scripts/output/AkhyataChandrika_Autogenerated.json \
    Scripts/output/multiple_dhatu_ids.yaml

if [ $? -ne 0 ]; then
    echo "❌ Error: Failed to collect multiple dhatu_ids"
    exit 1
fi

echo ""
echo "✅ Collection complete!"
echo ""

# Step 2: Show sample entries
echo "Step 2: Showing sample entries from multiple_dhatu_ids.yaml..."
head -n 50 Scripts/output/multiple_dhatu_ids.yaml
echo ""

# Step 3: Inform user about manual editing
echo "======================================================================"
echo "📝 Next Steps:"
echo "======================================================================"
echo ""
echo "1. Manually edit Scripts/output/multiple_dhatu_ids.yaml"
echo "   - Change the 'dhatu_ids' field to the correct single dhatu_id"
echo "   - Remove the comma-separated values and keep only the correct one"
echo ""
echo "2. Run the backport script to sync changes:"
echo "   python3 Scripts/backportMultipleDhatuIds.py \\"
echo "       Scripts/output/multiple_dhatu_ids.yaml \\"
echo "       Data"
echo ""
echo "3. Regenerate the JSON from updated YAML files"
echo ""
echo "======================================================================"
