#!/bin/bash
# Complete workflow example for handling multiple dhatu_ids
# This script demonstrates the full workflow from collection to backport

set -e  # Exit on error

echo "======================================================================"
echo "Multiple Dhatu IDs - Complete Workflow Example"
echo "======================================================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Step 1: Collect multiple dhatu_ids
echo -e "${BLUE}Step 1: Collecting verbs with multiple dhatu_ids...${NC}"
python3 Scripts/collectMultipleDhatuIds.py \
    Scripts/output/AkhyataChandrika_Autogenerated.json \
    Scripts/output/multiple_dhatu_ids.yaml

if [ $? -ne 0 ]; then
    echo "❌ Error: Failed to collect multiple dhatu_ids"
    exit 1
fi

echo ""
echo -e "${GREEN}✅ Collection complete!${NC}"
echo ""

# Show statistics
echo -e "${BLUE}Statistics:${NC}"
TOTAL_ENTRIES=$(grep -c "^\".*\":$" Scripts/output/multiple_dhatu_ids.yaml || echo "0")
echo "  Total entries found: $TOTAL_ENTRIES"
echo ""

# Show first few entries
echo -e "${BLUE}First 3 entries from multiple_dhatu_ids.yaml:${NC}"
echo "----------------------------------------------------------------------"
head -n 30 Scripts/output/multiple_dhatu_ids.yaml
echo "----------------------------------------------------------------------"
echo ""

# Step 2: Instructions for manual editing
echo -e "${YELLOW}======================================================================"
echo "Step 2: MANUAL EDITING REQUIRED"
echo "======================================================================${NC}"
echo ""
echo "Please edit the file: Scripts/output/multiple_dhatu_ids.yaml"
echo ""
echo "For each entry, change the 'dhatu_ids' field from:"
echo "  dhatu_ids: \"01.0594, 01.0608\"    ← Multiple IDs"
echo "To:"
echo "  dhatu_ids: \"01.0594\"              ← Single correct ID"
echo ""
echo "Example:"
echo "----------------------------------------------------------------------"
cat <<'EOF'
Before:
  "फलति":
    "form": "फलति"
    "dhatu_ids": "01.0594, 01.0608"    ← Choose one
    "gati": ""
    ...

After:
  "फलति":
    "form": "फलति"
    "dhatu_ids": "01.0594"              ← Corrected
    "gati": ""
    ...
EOF
echo "----------------------------------------------------------------------"
echo ""
echo -e "${YELLOW}Press ENTER when you have finished editing the file...${NC}"
read -p ""

# Step 3: Backport changes
echo ""
echo -e "${BLUE}Step 3: Backporting changes to original YAML files...${NC}"
python3 Scripts/backportMultipleDhatuIds.py \
    Scripts/output/multiple_dhatu_ids.yaml \
    Data

if [ $? -ne 0 ]; then
    echo "❌ Error: Failed to backport changes"
    exit 1
fi

echo ""
echo -e "${GREEN}✅ Backport complete!${NC}"
echo ""

# Step 4: Next steps
echo -e "${BLUE}======================================================================"
echo "Step 4: Next Steps"
echo "======================================================================${NC}"
echo ""
echo "The original YAML files have been updated with your corrections."
echo ""
echo "You should now:"
echo "  1. Review the changes in the Data/ folder"
echo "  2. Regenerate the JSON from the updated YAML files"
echo "  3. Verify the JSON no longer contains '(More than one)' entries"
echo ""
echo -e "${GREEN}======================================================================"
echo "Workflow Complete!"
echo "======================================================================${NC}"
